version: "3"
services:
  app:
    build: ./frontend/
    ports:
      - "46875:3000"
  web:
    build: ./server/
    ports:
      - "46874:46874"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dfadb
    ports:
      - "5432:5432"